package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

/**
 * DishesAuthorsId generated by hbm2java
 */
public class DishesAuthorsId implements java.io.Serializable {

	private int dishId;
	private int authorId;

	public DishesAuthorsId() {
	}

	public DishesAuthorsId(int dishId, int authorId) {
		this.dishId = dishId;
		this.authorId = authorId;
	}

	public int getDishId() {
		return this.dishId;
	}

	public void setDishId(int dishId) {
		this.dishId = dishId;
	}

	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DishesAuthorsId))
			return false;
		DishesAuthorsId castOther = (DishesAuthorsId) other;

		return (this.getDishId() == castOther.getDishId()) && (this.getAuthorId() == castOther.getAuthorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDishId();
		result = 37 * result + this.getAuthorId();
		return result;
	}

}
