package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

/**
 * DishesIngredientsId generated by hbm2java
 */
public class DishesIngredientsId implements java.io.Serializable {

	private int dishId;
	private int ingredientId;

	public DishesIngredientsId() {
	}

	public DishesIngredientsId(int dishId, int ingredientId) {
		this.dishId = dishId;
		this.ingredientId = ingredientId;
	}

	public int getDishId() {
		return this.dishId;
	}

	public void setDishId(int dishId) {
		this.dishId = dishId;
	}

	public int getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(int ingredientId) {
		this.ingredientId = ingredientId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DishesIngredientsId))
			return false;
		DishesIngredientsId castOther = (DishesIngredientsId) other;

		return (this.getDishId() == castOther.getDishId()) && (this.getIngredientId() == castOther.getIngredientId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDishId();
		result = 37 * result + this.getIngredientId();
		return result;
	}

}
