package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import com.google.gson.annotations.Expose;

/**
 * DishesIngredients generated by hbm2java
 */
public class DishesIngredients implements java.io.Serializable {

	private DishesIngredientsId id;
	@Expose
	private Dishes dishes;
	@Expose
	private Ingredients ingredients;
	@Expose
	private short quantity;

	public DishesIngredients() {
	}

	public DishesIngredients(DishesIngredientsId id, Dishes dishes, Ingredients ingredients, short quantity) {
		this.id = id;
		this.dishes = dishes;
		this.ingredients = ingredients;
		this.quantity = quantity;
	}

	public DishesIngredientsId getId() {
		return this.id;
	}

	public void setId(DishesIngredientsId id) {
		this.id = id;
	}

	public Dishes getDishes() {
		return this.dishes;
	}

	public void setDishes(Dishes dishes) {
		this.dishes = dishes;
	}

	public Ingredients getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Ingredients ingredients) {
		this.ingredients = ingredients;
	}

	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

}
