package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import com.google.gson.annotations.Expose;

/**
 * DishesAuthors generated by hbm2java
 */
public class DishesAuthors implements java.io.Serializable {

	private DishesAuthorsId id;
	@Expose
	private Authors authors;
	@Expose
	private Dishes dishes;
	@Expose
	private short rating;

	public DishesAuthors() {
	}

	public DishesAuthors(DishesAuthorsId id, Authors authors, Dishes dishes, short rating) {
		this.id = id;
		this.authors = authors;
		this.dishes = dishes;
		this.rating = rating;
	}

	public DishesAuthorsId getId() {
		return this.id;
	}

	public void setId(DishesAuthorsId id) {
		this.id = id;
	}

	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	public Dishes getDishes() {
		return this.dishes;
	}

	public void setDishes(Dishes dishes) {
		this.dishes = dishes;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
