package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;

import com.google.gson.annotations.Expose;

/**
 * Dishes generated by hbm2java
 */
public class Dishes implements java.io.Serializable {
	
	@Expose
	private int id;
	@Expose
	private String name;
	private int time;
	@Expose
	private String category;
	@Expose
	private String cuisine;
	@Expose
	private String description;
	

	private Set dishesIngredientses = new HashSet(0);
	private Set dishesAuthorses = new HashSet(0);
	private Set menusesForDishAppetizer = new HashSet(0);
	private Set menusesForDishDessert = new HashSet(0);
	private Set menusesForDishMainCourse = new HashSet(0);

	public Dishes() {
	}

	public Dishes(int id, String name, int time, String category, String cuisine, String description) {
		this.id = id;
		this.name = name;
		this.time = time;
		this.category = category;
		this.cuisine = cuisine;
		this.description = description;
	}

	public Dishes(int id, String name, int time, String category, String cuisine, String description,
			Set dishesIngredientses, Set dishesAuthorses, Set menusesForDishAppetizer, Set menusesForDishDessert,
			Set menusesForDishMainCourse) {
		this.id = id;
		this.name = name;
		this.time = time;
		this.category = category;
		this.cuisine = cuisine;
		this.description = description;
		this.dishesIngredientses = dishesIngredientses;
		this.dishesAuthorses = dishesAuthorses;
		this.menusesForDishAppetizer = menusesForDishAppetizer;
		this.menusesForDishDessert = menusesForDishDessert;
		this.menusesForDishMainCourse = menusesForDishMainCourse;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCuisine() {
		return this.cuisine;
	}

	public void setCuisine(String cuisine) {
		this.cuisine = cuisine;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(cascade=CascadeType.ALL, fetch = FetchType.EAGER, mappedBy="Dishes")
	public Set getDishesIngredientses() {
		return this.dishesIngredientses;
	}

	public void setDishesIngredientses(Set dishesIngredientses) {
		this.dishesIngredientses = dishesIngredientses;
	}

	@ManyToMany(cascade=CascadeType.ALL, fetch = FetchType.EAGER, mappedBy="Dishes")
	public Set getDishesAuthorses() {
		return this.dishesAuthorses;
	}

	public void setDishesAuthorses(Set dishesAuthorses) {
		this.dishesAuthorses = dishesAuthorses;
	}

	@ManyToMany(cascade=CascadeType.ALL, fetch = FetchType.EAGER, mappedBy="Dishes")
	public Set getMenusesForDishAppetizer() {
		return this.menusesForDishAppetizer;
	}

	public void setMenusesForDishAppetizer(Set menusesForDishAppetizer) {
		this.menusesForDishAppetizer = menusesForDishAppetizer;
	}

	@ManyToMany(cascade=CascadeType.ALL, fetch = FetchType.EAGER, mappedBy="Dishes")
	public Set getMenusesForDishDessert() {
		return this.menusesForDishDessert;
	}

	public void setMenusesForDishDessert(Set menusesForDishDessert) {
		this.menusesForDishDessert = menusesForDishDessert;
	}

	@ManyToMany(cascade=CascadeType.ALL, fetch = FetchType.EAGER, mappedBy="Dishes")
	public Set getMenusesForDishMainCourse() {
		return this.menusesForDishMainCourse;
	}

	public void setMenusesForDishMainCourse(Set menusesForDishMainCourse) {
		this.menusesForDishMainCourse = menusesForDishMainCourse;
	}

}
