package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Ingredients generated by hbm2java
 */
public class Ingredients implements java.io.Serializable {

	@Expose
	private int id;
	@Expose
	private String name;
	private Set dishesIngredientses = new HashSet(0);

	public Ingredients() {
	}

	public Ingredients(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Ingredients(int id, String name, Set dishesIngredientses) {
		this.id = id;
		this.name = name;
		this.dishesIngredientses = dishesIngredientses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDishesIngredientses() {
		return this.dishesIngredientses;
	}

	public void setDishesIngredientses(Set dishesIngredientses) {
		this.dishesIngredientses = dishesIngredientses;
	}

}
