package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Menus generated by hbm2java
 */
public class Menus implements java.io.Serializable {

	@Expose
	private int id;
	@Expose
	private Dishes dishesByDishAppetizer;
	@Expose
	private Dishes dishesByDishDessert;
	@Expose
	private Dishes dishesByDishMainCourse;
	private Set usersMenuses = new HashSet(0);

	public Menus() {
	}

	public Menus(int id, Dishes dishesByDishAppetizer, Dishes dishesByDishDessert, Dishes dishesByDishMainCourse) {
		this.id = id;
		this.dishesByDishAppetizer = dishesByDishAppetizer;
		this.dishesByDishDessert = dishesByDishDessert;
		this.dishesByDishMainCourse = dishesByDishMainCourse;
	}

	public Menus(int id, Dishes dishesByDishAppetizer, Dishes dishesByDishDessert, Dishes dishesByDishMainCourse,
			Set usersMenuses) {
		this.id = id;
		this.dishesByDishAppetizer = dishesByDishAppetizer;
		this.dishesByDishDessert = dishesByDishDessert;
		this.dishesByDishMainCourse = dishesByDishMainCourse;
		this.usersMenuses = usersMenuses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Dishes getDishesByDishAppetizer() {
		return this.dishesByDishAppetizer;
	}

	public void setDishesByDishAppetizer(Dishes dishesByDishAppetizer) {
		this.dishesByDishAppetizer = dishesByDishAppetizer;
	}

	public Dishes getDishesByDishDessert() {
		return this.dishesByDishDessert;
	}

	public void setDishesByDishDessert(Dishes dishesByDishDessert) {
		this.dishesByDishDessert = dishesByDishDessert;
	}

	public Dishes getDishesByDishMainCourse() {
		return this.dishesByDishMainCourse;
	}

	public void setDishesByDishMainCourse(Dishes dishesByDishMainCourse) {
		this.dishesByDishMainCourse = dishesByDishMainCourse;
	}

	public Set getUsersMenuses() {
		return this.usersMenuses;
	}

	public void setUsersMenuses(Set usersMenuses) {
		this.usersMenuses = usersMenuses;
	}

}
