package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

/**
 * UsersMenusId generated by hbm2java
 */
public class UsersMenusId implements java.io.Serializable {

	private int userId;
	private int menuId;

	public UsersMenusId() {
	}

	public UsersMenusId(int userId, int menuId) {
		this.userId = userId;
		this.menuId = menuId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersMenusId))
			return false;
		UsersMenusId castOther = (UsersMenusId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getMenuId() == castOther.getMenuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getMenuId();
		return result;
	}

}
