package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	@Expose
	private int id;
	@Expose
	private String name;
	@Expose
	private String surname;
	@Expose
	private int age;
	@Expose
	private String email;
	@Expose
	private String gender;
	@Expose
	private String nationality;
	private Set usersMenuses = new HashSet(0);

	public Users() {
	}

	public Users(int id, String name, String surname, int age, String email, String gender, String nationality) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.age = age;
		this.email = email;
		this.gender = gender;
		this.nationality = nationality;
	}

	public Users(int id, String name, String surname, int age, String email, String gender, String nationality,
			Set usersMenuses) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.age = age;
		this.email = email;
		this.gender = gender;
		this.nationality = nationality;
		this.usersMenuses = usersMenuses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public Set getUsersMenuses() {
		return this.usersMenuses;
	}

	public void setUsersMenuses(Set usersMenuses) {
		this.usersMenuses = usersMenuses;
	}

}
