package hibernate;
// Generated 14-feb-2019 10:59:48 by Hibernate Tools 5.2.11.Final

import com.google.gson.annotations.Expose;

/**
 * UsersMenus generated by hbm2java
 */
public class UsersMenus implements java.io.Serializable {

	private UsersMenusId id;
	@Expose
	private Menus menus;
	@Expose
	private Users users;
	@Expose
	private String category;
	@Expose
	private short rating;

	public UsersMenus() {
	}

	public UsersMenus(UsersMenusId id, Menus menus, Users users, String category, short rating) {
		this.id = id;
		this.menus = menus;
		this.users = users;
		this.category = category;
		this.rating = rating;
	}

	public UsersMenusId getId() {
		return this.id;
	}

	public void setId(UsersMenusId id) {
		this.id = id;
	}

	public Menus getMenus() {
		return this.menus;
	}

	public void setMenus(Menus menus) {
		this.menus = menus;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

}
